### ISSUE TITLE
Western Australia (:au_wa) ANZAC Day 2015 not on Monday

### ISSUE THREAD

**Issue by jufemaiz** [alexdunae/holidays#127]
Although technically the public holiday is both Saturday 25th April and Monday 27th April (as per http://www.commerce.wa.gov.au/labour-relations/public-holidays-western-australia), the rule of "to_monday_if_weekend" is not working. Instead I'm seeing the following (all loaded):

```
{:date=>Sat, 25 Apr 2015, :name=>"ANZAC Day", :regions=>[:au]}
{:date=>Sat, 25 Apr 2015, :name=>"ANZAC Day", :regions=>[:au_nsw, :au_vic, :au_qld, :au_nt, :au_act, :au_sa, :au_tas]}
{:date=>Sat, 25 Apr 2015, :name=>"ANZAC Day", :regions=>[:au_wa, :nz]}
```

**Comment by jufemaiz** [comment]
Ah crap. :observed flag not applied. Appologies!

**Comment by ptrimble** [comment]
No worries! Always good to have people reporting stuff, especially new definitions.
