### ISSUE TITLE
will not install with "bundle install --local"

### ISSUE THREAD

**Issue by jabulile** [alexdunae/holidays#70]
Hi,

for some reason it keeps trying to fetch it from https://github.com/alexdunae/holidays

"bundle install --local

Fetching https://github.com/alexdunae/holidays
error: Failed connect to github.com:443; Connection timed out while accessing https://github.com/alexdunae/holidays/info/refs
fatal: HTTP request failed"

i'm on Ubuntu 12.04
gem -v
1.8.15

**Comment by ptrimble** [comment]
This doesn't seem like a holiday gem specific issue. I'm going to go ahead and close this, feel free to post another update if it is still happening and I would be happy to reopen.
