### ISSUE TITLE
Federal Reserve holidays incorrect

### ISSUE THREAD

**Issue by flynfish** [alexdunae/holidays#90]
It looks like the Fed holidays are incorrect based on this (shouldn't have christmas and new years eve):

http://www.federalreserve.gov/aboutthefed/k8.htm

I can submit a pull request if needed, just let me know.

**Comment by flynfish** [comment]
Good Friday should also not be included.

**Comment by ptrimble** [comment]
Thanks for reporting this! I'll take a look at this shortly.

**Comment by aripollak** [comment]
Any news on this? Would it be more likely to be fixed with a PR?

**Comment by flynfish** [comment]
@aripollak in the meantime this is how I fixed it:

```ruby
BusinessTime::Config.load("#{Rails.root}/config/business_time.yml")

# or you can configure it manually:  look at me!  I'm Tim Ferriss!
#  BusinessTime::Config.beginning_of_workday = "10:00 am"
#  BusinessTime::Config.end_of_workday = "11:30 am"
#  BusinessTime::Config.holidays << Date.parse("August 4th, 2010")

h = Holidays.between(Date.civil(Date.current.year, 1, 1), Date.civil(Date.current.year + 1, 12, 31), :federal_reserve, :observed)
# Eve days and good friday are not actually fed holidays
h.reject{|r| r[:name].include? "Eve" or r[:name].include? "Good Friday" }.map do |holiday|
  BusinessTime::Config.holidays << holiday[:date]
end

```

**Comment by ptrimble** [comment]
Sorry dudes, I'll try to take a look at this on the train ride home tonight.

**Comment by ptrimble** [comment]
Addressed here: https://github.com/alexdunae/holidays/pull/97

Thanks for your patience! Let me know if you spot anything wrong with what I've pushed up. I'll be pushing a new version of the gem a bit later tonight.
