### ISSUE TITLE
Inaguration Day isn't a Federal Reserve holiday

### ISSUE THREAD

**Issue by aripollak** [alexdunae/holidays#98]
The `federal_reserve` region currently counts Inaguration Day as a holiday, but according to [this](http://www.federalreserve.gov/aboutthefed/k8.htm) it's not (just the Governors Board being closed, which doesn't count), so I think it should be removed.
Also, it doesn't look like Independence Day should be using `to_monday_if_sunday`.

**Comment by ptrimble** [comment]
Oh! I saw the Board of Governors was closed, I thought it was the same thing. Shows what I know about the Fed. Thanks for double-checking.

I'll take a look at this probably tomorrow and push out a fix.

**Comment by aripollak** [comment]
Thanks for the quick response! Sorry I didn't catch this earlier in #90.

**Comment by ptrimble** [comment]
@aripollak What do you think about having Inauguration Day as an 'informal' holiday? With that it will only show up in the results if a person explicit states that they want to see informal holidays.

**Comment by ptrimble** [comment]
Maybe, I don't know. I guess I should admit again that I don't really know what 'Governors Board' being closed really means in practical terms. Do people think of 'Federal Reserve' holidays as bank holidays? Does the Governors Board being closed have anything to do with bank holidays? :fearful:

**Comment by ptrimble** [comment]
Lastly, why do you think that July 4th should not be using `to_monday_if_sunday`? Based on this I would think that we should:

```
For holidays falling on Sunday, all Federal Reserve offices will be closed the following Monday.
```

Am I reading this incorrectly?

**Comment by aripollak** [comment]
> Do people think of 'Federal Reserve' holidays as bank holidays?

Yes. Specifically in our case (and I assume what other people are using it for as well), we're using it to calculate an acceptable date to specify as an effective bank transfer date, since weekends and Federal Reserve holidays are not valid. Maybe there are certain narrow cases for needing Governors Board holidays, but I don't think most people would be using those.

> Lastly, why do you think that July 4th should not be using to_monday_if_sunday? Based on this I would think that we should:

Oh yeah, you're totally right. I was misreading the chart because of the one star for this year's July 4th, but that falls on a Saturday.

**Comment by ptrimble** [comment]
Okay! I'll go ahead and remove Inauguration Day entirely. PR forthcoming.

**Comment by ptrimble** [comment]
And here it is: https://github.com/alexdunae/holidays/pull/99

Want to give it a look-over? It's pretty small.

**Comment by ptrimble** [comment]
Handled in the above PR. Thanks @aripollak! Let me know if you spot anything else.

**Comment by ptrimble** [comment]
Oh, and I will release this sometime soon, I have caching feature I would also like to get out at the same time.

**Comment by flynfish** [comment]
:+1:  I agree that most people will probably be using this for closed bank holidays and that inauguration day was properly removed. Thanks for the update!
